### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dohliam** [premasagar/js1k#1]
Hi premasagar, thanks for sharing your js1k entry! :+1: I notice you haven't included a license. Would it be possible to release this under a free license so that it can be included in the [openjs1k](https://github.com/dohliam/openjs1k) project? Even if you don't plan on using a free license, having a license of some kind would help people know whether or not they can reuse your work. :smile:

**Comment by premasagar** [comment]
I've added an MIT license in 8209778e7d
Thanks for the prompt and good one on the project.
